use_frameworks!

target 'SwiftPromises_Example' do
  pod 'SwiftPromises', :path => '../'

  target 'SwiftPromises_Tests' do
    inherit! :search_paths
    pod 'SwiftPromises', :path => '../'
  end
end
